### PR TITLE
Enhance best case worst case at both product and company level

### LINKED ISSUE #247: Implement "best case" and "worst case" for `sector_profile()` on product-level
Dear @kalashsinghal , 

please apply the best case / worst case logic from [#242](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/242) to the `sector_profile()` results (categories low, medium, high).

### LINKED ISSUE #313: Enhance best- / worst-case methodology: Use best / worst products instead of categories

### PR DESCRIPTION
**Pull request by kalashsinghal**
* closes #313 
* closes #247 

Dear @Tilmon @AnneSchoenauer,

This PR enhances the best case and worst case methodology for `emission_profile`, `sector_profile`, and `transition_risk_profile` as asked by @Tilmon. This PR also adds the best case and worst case for sector profile at product level before adding best case and wort case at company level. 

Please review the new methodology using below reprex for `emission_profile`! Similar methodological change is done also for `transition_risk_profile` and `sector_profile`. 

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(tiltToyData, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)
devtools::load_all(".")
#> ℹ Loading tiltIndicatorAfter
options(width = 5000)

example_data_product <- example_best_case_worst_case_profile_ranking_product_level(
  benchmark = c("all", "all", "unit"),
  profile_ranking = c(1.0, 2.0, NA)
)
example_data_product
#> # A tibble: 3 × 5
#>   benchmark profile_ranking companies_id ep_product emission_profile
#>   <chr>               <dbl> <chr>        <chr>      <chr>           
#> 1 all                     1 any          one        low             
#> 2 all                     2 any          two        medium          
#> 3 unit                   NA any          three      high

example_data_company <- example_best_case_worst_case_profile_ranking_company_level()
example_data_company
#> # A tibble: 3 × 3
#>   companies_id benchmark   profile_ranking_avg
#>   <chr>        <chr>                     <dbl>
#> 1 any          all                           5
#> 2 any          unit                          6
#> 3 any          tilt_sector                   7

input <- tilt_profile(nest_levels(example_data_product, example_data_company))
out <- input |>
  best_case_worst_case_emission_profile() |>
  best_case_worst_case_avg_profile_ranking()

case_product <- out |> unnest_product()
case_company <- out |> unnest_company()

case_product
#> # A tibble: 3 × 10
#>   companies_id benchmark profile_ranking ep_product emission_profile amount_of_distinct_products amount_of_distinct_products_matched emissions_profile_equal_weight emissions_profile_best_case emissions_profile_worst_case
#>   <chr>        <chr>               <dbl> <chr>      <chr>                                  <int>                               <int>                          <dbl>                       <dbl>                        <dbl>
#> 1 any          all                     1 one        low                                        3                                   2                            0.5                           1                           NA
#> 2 any          all                     2 two        medium                                     3                                   2                            0.5                          NA                            2
#> 3 any          unit                   NA three      high                                       3                                   1                            1                            NA                           NA

case_company
#> # A tibble: 3 × 5
#>   companies_id benchmark   profile_ranking_avg avg_profile_ranking_best_case avg_profile_ranking_worst_case
#>   <chr>        <chr>                     <dbl>                         <dbl>                          <dbl>
#> 1 any          all                           5                             1                              2
#> 2 any          unit                          6                            NA                             NA
#> 3 any          tilt_sector                   7                            NA                             NA
```

<sup>Created on 2024-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

----

Please let me know if you need a better example with different input data to understand this change! Thanks!

TODO

- [x] [Link related issue/PR]([url](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). 
- [x] Describe the goal of the PR. Avoid details that are clear in the diff.
- [x] Mark the PR as draft.
- [x] [Include a unit test](https://code-review.tidyverse.org/reviewer/aspects.html#sec-tests).
- [x] Review your own PR in "Files changed".
- [x] Ensure the PR branch is updated.
- [x] Ensure the checks pass.
- [x] Change the status from draft to ready.
- [x] Polish the PR description to reflect what it ended up doing.
- [x] Polish the PR title as you'd like others to read it from the git log.
- [x] Assign a reviewer.
- [ ] Document user-facing changes in the changelog.

### CODE REVIEW

**Comment by AnneSchoenauer** [comment]
Hi @kalash :) thanks a lot for this. 
I need to admit that it is a bit hard for me to understand because I am not quite sure if we have three companies in this example that all have the three products?! Could you maybe make this clear with specifying the id „any“? I think this will help. Also how can it be that we have profile ranks 1 and 2 on product level and then averages such as 5, 6 and 7 on company level this doesn’t add up right? So maybe good to have an example with three to four products and then one company that produces these four products. Thanks!

**Comment by Tilmon** [comment]
Hi @kalashsinghal addition from my side: Can you also make sure that the sample data have at least two products in the lowest and highest category, maybe one time with the same rank, once with different ranks? Right now we only have one product per category, hence it's not ideal to see the different behavior to the previous approach where you calculated best/worst case based on categories.
Thanks!

**Comment by kalashsinghal** [comment]
@AnneSchoenauer @Tilmon My bad!

Here is the updated reprex which addresses all your comments:

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(tiltToyData, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)
devtools::load_all(".")
#> ℹ Loading tiltIndicatorAfter
options(width = 5000)

example_data_product <- example_best_case_worst_case_profile_ranking_product_level(
  companies_id = c("comp_1", "comp_1", "comp_1", "comp_1", "comp_1", "comp_1"),
  benchmark = c("all", "all", "all", "unit", "unit", "unit"),
  ep_product = c("one", "two", "three", "one", "two", "three"),
  emission_profile = c("low", "high", "medium", "high", "low", "medium"),
  profile_ranking = c(1.0, 7.0, 2.0, 9.0, 1.0, 4.0)
)
example_data_product
#> # A tibble: 6 × 5
#>   companies_id benchmark ep_product emission_profile profile_ranking
#>   <chr>        <chr>     <chr>      <chr>                      <dbl>
#> 1 comp_1       all       one        low                            1
#> 2 comp_1       all       two        high                           7
#> 3 comp_1       all       three      medium                         2
#> 4 comp_1       unit      one        high                           9
#> 5 comp_1       unit      two        low                            1
#> 6 comp_1       unit      three      medium                         4

example_data_company <- example_best_case_worst_case_profile_ranking_company_level(
  companies_id = c("comp_1", "comp_1"),
  benchmark = c("all", "unit"),
  profile_ranking_avg = c(5.0, 7.0)
)
example_data_company
#> # A tibble: 2 × 3
#>   companies_id benchmark profile_ranking_avg
#>   <chr>        <chr>                   <dbl>
#> 1 comp_1       all                         5
#> 2 comp_1       unit                        7

input <- tilt_profile(nest_levels(example_data_product, example_data_company))
out <- input |>
  best_case_worst_case_emission_profile() |>
  best_case_worst_case_avg_profile_ranking()

case_product <- out |> unnest_product()
case_company <- out |> unnest_company()

case_product
#> # A tibble: 6 × 10
#>   companies_id benchmark ep_product emission_profile profile_ranking amount_of_distinct_products amount_of_distinct_products_matched emissions_profile_equal_weight emissions_profile_best_case emissions_profile_worst_case
#>   <chr>        <chr>     <chr>      <chr>                      <dbl>                       <int>                               <int>                          <dbl>                       <dbl>                        <dbl>
#> 1 comp_1       all       one        low                            1                           3                                   3                          0.333                           1                           NA
#> 2 comp_1       all       two        high                           7                           3                                   3                          0.333                          NA                            7
#> 3 comp_1       all       three      medium                         2                           3                                   3                          0.333                          NA                           NA
#> 4 comp_1       unit      one        high                           9                           3                                   3                          0.333                          NA                            9
#> 5 comp_1       unit      two        low                            1                           3                                   3                          0.333                           1                           NA
#> 6 comp_1       unit      three      medium                         4                           3                                   3                          0.333                          NA                           NA

case_company
#> # A tibble: 2 × 5
#>   companies_id benchmark profile_ranking_avg avg_profile_ranking_best_case avg_profile_ranking_worst_case
#>   <chr>        <chr>                   <dbl>                         <dbl>                          <dbl>
#> 1 comp_1       all                         5                             1                              7
#> 2 comp_1       unit                        7                             1                              9
```

<sup>Created on 2024-10-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Tilmon** [comment]
@kalashsinghal thanks for this! 

1. I think the average profile rank is wrong. Why is it 5 and 7? Shouldn't it be for `all` 10/3 and for `unit` 14/3? I think you only divided by 2 instead. 
2. Why are ranks > 1? Does this impact the results? Could you, just to be more realistic, divide the ranks by 10 so that they are between 0 and 1? 
3. Can you, just to be sure, also provide a reprex that contains a company with two products that have the same rank? 

Other than that, it looks good to me! Thanks!

**Comment by kalashsinghal** [comment]
Hi @Tilmon,

Thanks for your review! It helped me to resolve an internal code issue :). Here is another reprex which addresses all your above comments:

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(tiltToyData, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)
devtools::load_all(".")
#> ℹ Loading tiltIndicatorAfter
options(width = 5000)

example_data_product <- example_best_case_worst_case_profile_ranking_product_level(
  companies_id = c("comp_1", "comp_1", "comp_1", "comp_1", "comp_1", "comp_1"),
  benchmark = c("all", "all", "all", "unit", "unit", "unit"),
  ep_product = c("one", "two", "three", "one", "two", "three"),
  emission_profile = c("low", "low", "medium", "high", "low", "medium"),
  profile_ranking = c(0.2, 0.2, 0.4, 0.9, 0.1, 0.4)
)
example_data_product
#> # A tibble: 6 × 5
#>   companies_id benchmark ep_product emission_profile profile_ranking
#>   <chr>        <chr>     <chr>      <chr>                      <dbl>
#> 1 comp_1       all       one        low                          0.2
#> 2 comp_1       all       two        low                          0.2
#> 3 comp_1       all       three      medium                       0.4
#> 4 comp_1       unit      one        high                         0.9
#> 5 comp_1       unit      two        low                          0.1
#> 6 comp_1       unit      three      medium                       0.4
  
example_data_company <- example_best_case_worst_case_profile_ranking_company_level(
  companies_id = c("comp_1", "comp_1"),
  benchmark = c("all", "unit"),
  profile_ranking_avg = c(0.8/3, 1.4/3)
)
example_data_company
#> # A tibble: 2 × 3
#>   companies_id benchmark profile_ranking_avg
#>   <chr>        <chr>                   <dbl>
#> 1 comp_1       all                     0.267
#> 2 comp_1       unit                    0.467

input <- tilt_profile(nest_levels(example_data_product, example_data_company))
out <- input |>
  best_case_worst_case_emission_profile() |>
  best_case_worst_case_avg_profile_ranking()

case_product <- out |> unnest_product()
case_company <- out |> unnest_company()

case_product
#> # A tibble: 6 × 10
#>   companies_id benchmark ep_product emission_profile profile_ranking amount_of_distinct_products amount_of_distinct_products_matched emissions_profile_equal_weight emissions_profile_best_case emissions_profile_worst_case
#>   <chr>        <chr>     <chr>      <chr>                      <dbl>                       <int>                               <int>                          <dbl>                       <dbl>                        <dbl>
#> 1 comp_1       all       one        low                          0.2                           3                                   3                          0.333                         0.2                         NA  
#> 2 comp_1       all       two        low                          0.2                           3                                   3                          0.333                         0.2                         NA  
#> 3 comp_1       all       three      medium                       0.4                           3                                   3                          0.333                        NA                            0.4
#> 4 comp_1       unit      one        high                         0.9                           3                                   3                          0.333                        NA                            0.9
#> 5 comp_1       unit      two        low                          0.1                           3                                   3                          0.333                         0.1                         NA  
#> 6 comp_1       unit      three      medium                       0.4                           3                                   3                          0.333                        NA                           NA

case_company
#> # A tibble: 2 × 5
#>   companies_id benchmark profile_ranking_avg avg_profile_ranking_best_case avg_profile_ranking_worst_case
#>   <chr>        <chr>                   <dbl>                         <dbl>                          <dbl>
#> 1 comp_1       all                     0.267                           0.2                            0.4
#> 2 comp_1       unit                    0.467                           0.1                            0.9
```

<sup>Created on 2024-10-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please check the `all` benchmark for which products `one` and `two` have same profile rank of `0.2`. Please let me know if you have additional questions! Thanks!

**Comment by Tilmon** [comment]
@kalashsinghal looks good to me! :)

**Pull request merged**
