### PR TITLE
`profile_*()` now yield objects of class 'tilt_profile'

### PR DESCRIPTION
**Pull request by maurolepore**
* Relates to 2DegreesInvesting/tiltIndicator#768

This enables polymorphic behavior. For an example see the reprex.

<details/>
<summary/>
reprex
</summary>

``` r
library(tiltToyData)
library(readr, warn.conflicts = FALSE)
devtools::load_all()
#> ℹ Loading tiltIndicatorAfter

withr::local_options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
co2 <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

result <- profile_emissions(
  companies,
  co2,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)
#> ℹ Adding 62% and 76% noise to `co2e_lower` and `co2e_upper`, respectively.

# INTERESTING

# Consider function that returns the output at product level
use_product <- function(data) {
  unnest_product(data)
}

# It works well if the `data` is the result of `profile_emissions()` ...
use_product(result)
#> # A tibble: 456 × 25
#>    companies_id       company_name country emission_profile benchmark ep_product
#>    <chr>              <chr>        <chr>   <chr>            <chr>     <chr>     
#>  1 asteria_megalotom… asteria_meg… austria high             all       tent      
#>  2 asteria_megalotom… asteria_meg… austria high             isic_4di… tent      
#>  3 asteria_megalotom… asteria_meg… austria high             tilt_sec… tent      
#>  4 asteria_megalotom… asteria_meg… austria high             unit      tent      
#>  5 asteria_megalotom… asteria_meg… austria high             unit_isi… tent      
#>  6 asteria_megalotom… asteria_meg… austria high             unit_til… tent      
#>  7 skarn_gallinule    skarn_galli… austria high             all       sheds, co…
#>  8 skarn_gallinule    skarn_galli… austria high             isic_4di… sheds, co…
#>  9 skarn_gallinule    skarn_galli… austria high             tilt_sec… sheds, co…
#> 10 skarn_gallinule    skarn_galli… austria high             unit      sheds, co…
#> # ℹ 446 more rows
#> # ℹ 19 more variables: matched_activity_name <chr>,
#> #   matched_reference_product <chr>, co2e_lower <dbl>, co2e_upper <dbl>,
#> #   unit <chr>, multi_match <lgl>, matching_certainty <chr>,
#> #   matching_certainty_company_average <chr>, tilt_sector <chr>,
#> #   tilt_subsector <chr>, isic_4digit <chr>, isic_4digit_name <chr>,
#> #   company_city <chr>, postcode <chr>, address <chr>, main_activity <chr>, …

# ... but it fails if the `data` is already a `product` level result
product <- unnest_product(result)
use_product(product)
#> Error in `select()`:
#> ! Can't select columns that don't exist.
#> ✖ Column `company` doesn't exist.

# This is annoying! We can do better using the 'tilt_profile' class
use_product <- function(data) {
  UseMethod("use_product")
}
use_product.tilt_profile <- function(data) {
  unnest_product(data)
}
use_product.data.frame <- function(data) data

# This is now polymorphic.
class(result)
#> [1] "tilt_profile" "tbl_df"       "tbl"          "data.frame"
use_product(result)
#> # A tibble: 456 × 25
#>    companies_id       company_name country emission_profile benchmark ep_product
#>    <chr>              <chr>        <chr>   <chr>            <chr>     <chr>     
#>  1 asteria_megalotom… asteria_meg… austria high             all       tent      
#>  2 asteria_megalotom… asteria_meg… austria high             isic_4di… tent      
#>  3 asteria_megalotom… asteria_meg… austria high             tilt_sec… tent      
#>  4 asteria_megalotom… asteria_meg… austria high             unit      tent      
#>  5 asteria_megalotom… asteria_meg… austria high             unit_isi… tent      
#>  6 asteria_megalotom… asteria_meg… austria high             unit_til… tent      
#>  7 skarn_gallinule    skarn_galli… austria high             all       sheds, co…
#>  8 skarn_gallinule    skarn_galli… austria high             isic_4di… sheds, co…
#>  9 skarn_gallinule    skarn_galli… austria high             tilt_sec… sheds, co…
#> 10 skarn_gallinule    skarn_galli… austria high             unit      sheds, co…
#> # ℹ 446 more rows
#> # ℹ 19 more variables: matched_activity_name <chr>,
#> #   matched_reference_product <chr>, co2e_lower <dbl>, co2e_upper <dbl>,
#> #   unit <chr>, multi_match <lgl>, matching_certainty <chr>,
#> #   matching_certainty_company_average <chr>, tilt_sector <chr>,
#> #   tilt_subsector <chr>, isic_4digit <chr>, isic_4digit_name <chr>,
#> #   company_city <chr>, postcode <chr>, address <chr>, main_activity <chr>, …

class(product)
#> [1] "tbl_df"     "tbl"        "data.frame"
use_product(product)
#> # A tibble: 456 × 25
#>    companies_id       company_name country emission_profile benchmark ep_product
#>    <chr>              <chr>        <chr>   <chr>            <chr>     <chr>     
#>  1 asteria_megalotom… asteria_meg… austria high             all       tent      
#>  2 asteria_megalotom… asteria_meg… austria high             isic_4di… tent      
#>  3 asteria_megalotom… asteria_meg… austria high             tilt_sec… tent      
#>  4 asteria_megalotom… asteria_meg… austria high             unit      tent      
#>  5 asteria_megalotom… asteria_meg… austria high             unit_isi… tent      
#>  6 asteria_megalotom… asteria_meg… austria high             unit_til… tent      
#>  7 skarn_gallinule    skarn_galli… austria high             all       sheds, co…
#>  8 skarn_gallinule    skarn_galli… austria high             isic_4di… sheds, co…
#>  9 skarn_gallinule    skarn_galli… austria high             tilt_sec… sheds, co…
#> 10 skarn_gallinule    skarn_galli… austria high             unit      sheds, co…
#> # ℹ 446 more rows
#> # ℹ 19 more variables: matched_activity_name <chr>,
#> #   matched_reference_product <chr>, co2e_lower <dbl>, co2e_upper <dbl>,
#> #   unit <chr>, multi_match <lgl>, matching_certainty <chr>,
#> #   matching_certainty_company_average <chr>, tilt_sector <chr>,
#> #   tilt_subsector <chr>, isic_4digit <chr>, isic_4digit_name <chr>,
#> #   company_city <chr>, postcode <chr>, address <chr>, main_activity <chr>, …
```

</details>

----

TODO

- [x] [Link related issue/PR]([url](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). 
- [x] Describe the goal of the PR. Avoid details that are clear in the diff.
- [x] Mark the PR as draft.
- [x] [Include a unit test](https://code-review.tidyverse.org/reviewer/aspects.html#sec-tests).
- [x] Review your own PR in "Files changed".
- [x] Ensure the PR branch is updated.
- [x] Ensure the checks pass.
- [x] Change the status from draft to ready.
- [x] Polish the PR title and description.
- [x] Assign a reviewer.

EXCEPTIONS

- [ ] Slide here any item that you intentionally choose to not do.

### CODE REVIEW

**Comment by kalashsinghal** [comment]
@maurolepore Interesting stuff!!

How converting an object to class `profile` helps us in conserving the `product` and `company` level columns after applying the `nest_levels` function?

**Review by kalashsinghal — APPROVED** [review]
@maurolepore LGTM!

**Comment by maurolepore** [comment]
Note:

* `raw` is a 'tilt_profile' and can be easily used in a pipe including functions that work only at product level (e.g. `summarize_co2_range()`). 
* `raw` is also piped into `exclude()`, which also has a method for 'tilt_profile' which excludes a column and duplicates from both levels at the same time.
* `join_to()` in this example is happily joining a data frame with a 'tilt_profile'.

```r
final <- raw |>
  summarize_co2_range() |>
  jitter_co2_range(amount = 1) |>
  polish_co2_range() |>
  join_to(raw |> exclude("co2_footprint"))
```

**Comment by maurolepore** [comment]
@kalashsinghal 


BTW, I'm using the most common, light-weight OOO system in R (S3). It's well documented [here](https://adv-r.hadley.nz/s3.html).

> S3 is R’s first and simplest OO system. ... You should use it, unless you have a compelling reason to do otherwise. S3 is the only OO system used in the base and stats packages, and it’s the most commonly used system in CRAN packages.

https://adv-r.hadley.nz/oo-tradeoffs.html

You'll see it's very different to what you might have seen in Python -- which I guess is closer to R6

> R6 is a profoundly different OO system from S3 and S4 because it is built on encapsulated objects, rather than generic functions. Additionally R6 objects have reference semantics, which means that they can be modified in place. 

https://adv-r.hadley.nz/oo-tradeoffs.html#s3-r6

**Pull request merged**
