### PR TITLE
At product level, `profile_emissions()` now preserves missing benchmarks

### PR DESCRIPTION
**Pull request by maurolepore**
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-2009503324 (see there a reprex before).

@Tilmon please do a conceptual review based on this reprex. While you're here please also review the output at company level. You'll see weird `NaN` which we could convert to more commonly seen `NA`.

<details/>
<summary/>
reprex
</summary>

``` r
# SETUP --------------------------------------------------------------------
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(tiltToyData)
library(tiltIndicator)

devtools::load_all()
#> ℹ Loading tiltIndicatorAfter

withr::local_options(readr.show_col_types = FALSE, width = 500)

companies <- read_csv(toy_emissions_profile_any_companies())
id <- unique(companies$companies_id)[[1]]
uuid <- unique(companies$activity_uuid_product_uuid)[[1]]
companies <- companies |>
  filter(companies_id == id) |>
  filter(activity_uuid_product_uuid == uuid)

co2 <- read_csv(toy_emissions_profile_products_ecoinvent()) |>
  filter(activity_uuid_product_uuid == uuid)
# Introduce a "missing benchmark"
co2$isic_4digit <- NA

europages_companies <- read_csv(toy_europages_companies()) |>
  filter(companies_id == id)
ecoinvent_activities <- read_csv(toy_ecoinvent_activities()) |>
  filter(activity_uuid_product_uuid == uuid)
ecoinvent_europages <- read_csv(toy_ecoinvent_europages()) |>
  filter(activity_uuid_product_uuid == uuid)
isic_name <- read_csv(toy_isic_name()) |>
  filter(isic_4digit == co2$isic_4digit)



# INTERESTING --------------------------------------------------------------

companies
#> # A tibble: 1 × 7
#>   activity_uuid_product_uuid           clustered companies_id        country ei_activity_name                                              main_activity unit 
#>   <chr>                                <chr>     <chr>               <chr>   <chr>                                                         <chr>         <chr>
#> 1 76269c17-78d6-420b-991a-aa38c51b45b7 tent      antimonarchy_canine germany market for shed, large, wood, non-insulated, fire-unprotected distributor   m2

co2 |> relocate(matches(c("isic")))
#> # A tibble: 1 × 8
#>   isic_4digit activity_uuid_product_uuid           co2_footprint ei_activity_name                                              ei_geography tilt_sector  tilt_subsector           unit 
#>   <lgl>       <chr>                                        <dbl> <chr>                                                         <chr>        <chr>        <chr>                    <chr>
#> 1 NA          76269c17-78d6-420b-991a-aa38c51b45b7          303. market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2

out <- profile_emissions(
  companies,
  co2,
  europages_companies,
  ecoinvent_activities,
  ecoinvent_europages,
  isic_name
)
#> ℹ Adding 68% and 119% noise to `co2e_lower` and `co2e_upper`, respectively.

out |> 
  unnest_product() |> 
  relocate(matches(c("benchmark", "ranking")))
#> # A tibble: 6 × 25
#>   benchmark        profile_ranking companies_id        company_name        country emission_profile ep_product matched_activity_name                                         matched_reference_product                          co2e_lower co2e_upper unit  multi_match matching_certainty matching_certainty_company_average tilt_sector  tilt_subsector           isic_4digit isic_4digit_name company_city postcode address                                    main_activity activity_uuid_product…¹ ei_geography
#>   <chr>                      <dbl> <chr>               <chr>               <chr>   <chr>            <chr>      <chr>                                                         <chr>                                                   <dbl>      <dbl> <chr> <lgl>       <chr>              <chr>                              <chr>        <chr>                    <chr>       <chr>            <chr>        <chr>    <chr>                                      <chr>         <chr>                   <chr>       
#> 1 all                            1 antimonarchy_canine antimonarchy_canine germany high             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected      127.        716. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 2 isic_4digit                   NA antimonarchy_canine antimonarchy_canine germany <NA>             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected     -112.        557. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 3 tilt_sector                    1 antimonarchy_canine antimonarchy_canine germany high             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected       15.8       316. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 4 unit                           1 antimonarchy_canine antimonarchy_canine germany high             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected     -112.        771. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 5 unit_isic_4digit              NA antimonarchy_canine antimonarchy_canine germany <NA>             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected     -186.        889. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 6 unit_tilt_sector               1 antimonarchy_canine antimonarchy_canine germany high             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected      -22.9       733. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid

# zoom
out |> 
  unnest_product() |> 
  filter(grepl("isic", benchmark)) |> 
  relocate(matches(c("benchmark", "ranking")))
#> # A tibble: 2 × 25
#>   benchmark        profile_ranking companies_id        company_name        country emission_profile ep_product matched_activity_name                                         matched_reference_product                          co2e_lower co2e_upper unit  multi_match matching_certainty matching_certainty_company_average tilt_sector  tilt_subsector           isic_4digit isic_4digit_name company_city postcode address                                    main_activity activity_uuid_product…¹ ei_geography
#>   <chr>                      <dbl> <chr>               <chr>               <chr>   <chr>            <chr>      <chr>                                                         <chr>                                                   <dbl>      <dbl> <chr> <lgl>       <chr>              <chr>                              <chr>        <chr>                    <chr>       <chr>            <chr>        <chr>    <chr>                                      <chr>         <chr>                   <chr>       
#> 1 isic_4digit                   NA antimonarchy_canine antimonarchy_canine germany <NA>             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected      -112.       557. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> 2 unit_isic_4digit              NA antimonarchy_canine antimonarchy_canine germany <NA>             tent       market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected      -186.       889. m2    FALSE       low                low                                construction construction residential <NA>        <NA>             hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor   76269c17-78d6-420b-991… tilt_world  
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid

out |> 
  unnest_company() |> 
  relocate(matches(c("benchmark", "ranking")))
#> # A tibble: 24 × 14
#>    benchmark   profile_ranking_avg companies_id        company_name        country emission_profile_share emission_profile co2e_lower co2e_upper matching_certainty_company_average company_city postcode address                                    main_activity
#>    <chr>                     <dbl> <chr>               <chr>               <chr>                    <dbl> <chr>                 <dbl>      <dbl> <chr>                              <chr>        <chr>    <chr>                                      <chr>        
#>  1 all                           1 antimonarchy_canine antimonarchy_canine germany                      1 high                  127.        716. low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  2 all                           1 antimonarchy_canine antimonarchy_canine germany                      0 medium                 NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  3 all                           1 antimonarchy_canine antimonarchy_canine germany                      0 low                    NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  4 all                           1 antimonarchy_canine antimonarchy_canine germany                      0 <NA>                   NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  5 isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 high                   NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  6 isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 medium                 NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  7 isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 low                    NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  8 isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      1 <NA>                 -112.        557. low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#>  9 tilt_sector                   1 antimonarchy_canine antimonarchy_canine germany                      1 high                   15.8       316. low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 10 tilt_sector                   1 antimonarchy_canine antimonarchy_canine germany                      0 medium                 NA          NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> # ℹ 14 more rows

# zoom
out |> 
  unnest_company() |> 
  filter(grepl("isic", benchmark)) |> 
  relocate(matches(c("benchmark", "ranking")))
#> # A tibble: 8 × 14
#>   benchmark        profile_ranking_avg companies_id        company_name        country emission_profile_share emission_profile co2e_lower co2e_upper matching_certainty_company_average company_city postcode address                                    main_activity
#>   <chr>                          <dbl> <chr>               <chr>               <chr>                    <dbl> <chr>                 <dbl>      <dbl> <chr>                              <chr>        <chr>    <chr>                                      <chr>        
#> 1 isic_4digit                      NaN antimonarchy_canine antimonarchy_canine germany                      0 high                    NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 2 isic_4digit                      NaN antimonarchy_canine antimonarchy_canine germany                      0 medium                  NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 3 isic_4digit                      NaN antimonarchy_canine antimonarchy_canine germany                      0 low                     NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 4 isic_4digit                      NaN antimonarchy_canine antimonarchy_canine germany                      1 <NA>                  -112.       557. low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 5 unit_isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 high                    NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 6 unit_isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 medium                  NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 7 unit_isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      0 low                     NA         NA  low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor  
#> 8 unit_isic_4digit                 NaN antimonarchy_canine antimonarchy_canine germany                      1 <NA>                  -186.       889. low                                hamburg      22525    schnackenburgallee 217-223 | 22525 hamburg distributor
```

</details>

----

TODO

- [x] [Link related issue/PR]([url](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). 
- [x] Describe the goal of the PR. Avoid details that are clear in the diff.
- [x] Mark the PR as draft.
- [x] [Include a unit test](https://code-review.tidyverse.org/reviewer/aspects.html#sec-tests).
- [x] Review your own PR in "Files changed".
- [x] Ensure the PR branch is updated.
- [x] Ensure the checks pass.
- [x] Change the status from draft to ready.
- [x] Polish the PR title and description.
- [x] Assign a reviewer.

EXCEPTIONS

- [ ] Slide here any item that you intentionally choose to not do.

### CODE REVIEW

**Comment by Tilmon** [comment]
@maurolepore good stuff, looks good to me! Both on product- and company-level. But the reprex only covers missing benchmarks right now, doesn't it? 

@AnneSchoenauer pls also have a look at this. 4 eyes see better than two ;)

**Comment by maurolepore** [comment]
> the reprex only covers missing benchmarks right now, doesn't it?

Correct. This is the PR that fixes that specific issue. Everything releates to that. In the tab [Files changed](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/196/files) you can see the specific code that changed, and the tests that prove the new behaviour. That technical aspect of the PR will be reviewed by Kalash but you may also want to look at it to become more familiar with that a PR contains. 

But I'm happy to share here an extended version of the top reprex, showing the behaviour with other products. If the package was comprehensively covered by tests, then those tests would ensure that none of the tested behaviour changed -- meaning that it's generally unecessary to show that the previous behaviour is maintained (else the checks section of this thread would shows failing checks).

**Comment by AnneSchoenauer** [comment]
Hi everyone, 
Thanks a lot @maurolepore - this looks really good with regard to the `NAs`! @Tilmon it would be nice if you have a double check again as I think I saw another reprex than you saw it.
Thanks @maurolepore and if @Tilmon gives the final go - you can go ahead and the @kalashsinghal can calculate the rest :)

**Comment by Tilmon** [comment]
@maurolepore

> But I'm happy to share here an extended version of the top reprex, showing the behaviour with other products. Here it is:

I'm a bit puzzled. I can only see cases of "missing benchmark" in the reprex you shared. Am I missing anything? I can see that in the PR https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/196/files there is a test for preserving unmatched products, but would be good to see how this looks in the output. 

Could you share such reprex?

**Review by kalashsinghal — DISMISSED** [review]
LGTM, however please merge this PR after completing conceptual review of Tilman. Thanks!

**Comment by maurolepore** [comment]
@Tilmon, yeah I suspect you might be looking at the "# zoom" tables only. You might be missing that the reprex shows two views of the output at product level and two views of the output at company level:

- Each "# zoom" view zooms into the output specific for this PR -- ie what relates to missing benchmarks.
- But before the "# zoom" view the reprex shows a few rows of the entire output, where you can see some output unrelated to the missing benchmarks.

Please look again and let me know if you still think the code is not doing what you expect.

You may also run the reprex in your own system if you prefer. Just remember to install the code from this PR -- not from the main branch.

**Comment by maurolepore** [comment]
@Tilmon 

Sorry for confusing you. You're right. I promised to extend the reprex to show the case of unmatched products and I forgot. My brain seems hard-wired to automatically focus the specific issue at hand. (BTW I edited the title of the PR to highlight it's about missing benchmark. I'll extract the irrelevant test into a separate PR and merge it to main.)

Second try ... hold on ...

**Comment by Tilmon** [comment]
Thanks @maurolepore ! I think the output on product-level looks now as we want it. @AnneSchoenauer can you please confirm?

**Comment by AnneSchoenauer** [comment]
Thanks! Yes i confirm that it looks good! 
@kalashsinghal when do you think you can generate the final outputs? Still today or tomorrow first thing?

**Comment by kalashsinghal** [comment]
@AnneSchoenauer Should I now also add `NA` benchmarks in the final output other than "all" and "unit_tilt_sector" for country "germany"?

**Comment by AnneSchoenauer** [comment]
Hi @kalashsinghal - no only for those two benchmarks. Could you instead of the benchmark all use the benchmark unit? Thanks!

**Pull request merged**
